/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const AccountInfo = IDL.Record({
  'earnedYield' : IDL.Float64,
  'balance' : IDL.Float64,
  'owner' : UserId,
  'totalWithdrawals' : IDL.Float64,
  'totalDeposits' : IDL.Float64,
});
export const DepositResult = IDL.Variant({
  'ok' : AccountInfo,
  'err' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const TransactionType = IDL.Variant({
  'deposit' : IDL.Null,
  'withdrawal' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'timestamp' : Timestamp,
  'txType' : TransactionType,
  'balanceAfter' : IDL.Float64,
  'amount' : IDL.Float64,
});
export const WithdrawalResult = IDL.Variant({
  'ok' : AccountInfo,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'deposit' : IDL.Func([IDL.Float64], [DepositResult], []),
  'getAccount' : IDL.Func([], [AccountInfo], []),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'withdraw' : IDL.Func([IDL.Float64], [WithdrawalResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const AccountInfo = IDL.Record({
    'earnedYield' : IDL.Float64,
    'balance' : IDL.Float64,
    'owner' : UserId,
    'totalWithdrawals' : IDL.Float64,
    'totalDeposits' : IDL.Float64,
  });
  const DepositResult = IDL.Variant({ 'ok' : AccountInfo, 'err' : IDL.Text });
  const Timestamp = IDL.Int;
  const TransactionType = IDL.Variant({
    'deposit' : IDL.Null,
    'withdrawal' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'timestamp' : Timestamp,
    'txType' : TransactionType,
    'balanceAfter' : IDL.Float64,
    'amount' : IDL.Float64,
  });
  const WithdrawalResult = IDL.Variant({
    'ok' : AccountInfo,
    'err' : IDL.Text,
  });
  
  return IDL.Service({
    'deposit' : IDL.Func([IDL.Float64], [DepositResult], []),
    'getAccount' : IDL.Func([], [AccountInfo], []),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'withdraw' : IDL.Func([IDL.Float64], [WithdrawalResult], []),
  });
};

export const init = ({ IDL }) => { return []; };